# -*- coding: utf-8 -*-
"""Deep Learning Capstone Project - 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ox1A-8lZfySyFM6lp8-wOLlx34GGq8aG
"""

Image Dataset - MNIST Dataset

### 1. Load and display the image
### 2 . Prepare the data
### 3. Training the neural network model (MLP Classifier)
## 4. Evaluate the model

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

mnist = fetch_openml('mnist_784',version=1)
X = mnist.data  ### (Images 784 features - 28x28 pixels)
y = mnist.target ### (Labels)

X.shape

X.iloc[50000]

### Show what is the image
image = X.iloc[50000].values.reshape(28,28)
plt.imshow(image, cmap='gray')
plt.title(y[50000])
plt.show()

for i in range(10):
  image = X.iloc[i].values.reshape(28,28)
  plt.imshow(image, cmap='gray')
  plt.title(y[i])
  plt.show()

### Normalize the data
### Covert the y (labels to integers)
y = y.astype('int')
y.shape

y.value_counts(normalize = True)*100   ### Dataset is quite balanced in their labels

### Before Normalization
X.iloc[0].values.reshape(28,28)

X = X/255.0   #### Scales with the highest pixels value
X

### After normalization
X.iloc[0].values.reshape(28,28)

### Split the data into training and Testing
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)
print(X_train.shape)
print(X_test.shape)
print(X_train.shape)
print(y_test.shape)

###Creating the neural network model
mlp = MLPClassifier(
    hidden_layer_sizes = (100),
    max_iter=20,  ### epochs
    activation = 'relu',
    solver = 'adam',
    random_state = 42,
    verbose=True)

mlp.fit(X_train, y_train)
print("Training of 56000 Images is done -------")

### Predictions
y_pred = mlp.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

### Test on sample image
sample = X_test.iloc[10].values.reshape(1,-1)
sample

prediction = mlp.predict(sample)
prediction

plt.imshow(sample.reshape(28,28), cmap='gray')
plt.title(f"Prediction: {prediction[0]}")
plt.show()

import joblib
joblib.dump(mlp, "mlp_modelv1.joblib")

### CPU and GPU
##CPU - Central processing unit - Brain(Designed to handle any kind of task)
##-- Few cores(typically  4-16) - Individual processing unit
## 4 core CPU/ 8 Core CPU - you can run 4 tasks parlelly / 8 tasks paralley
## Highly optimized for sequntial processing


### GPU - Graphic processing unit (1000 - 10000)
### There can be multiple small cores (thousands)
## Designed for parallel processing
## Executes many calculation at the same time

## Google colab is having CPU and GPU as well
### Cloud based jyuter notebook
### Free to access to GPU (with limits)
### No setup is

import tensorflow as tf
print("GPU Configuration - ",tf.config.list_physical_devices('GPU'))

### GPU details
!nvidia-smi

### GPU Type - T4,1000

import tensorflow as tf
print("GPU Configuration - ",tf.config.list_physical_devices('GPU'))

### GPU details
!nvidia-smi

### GPU Type - T4, A100
## Memory usage
### Processor

